# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: senigami
ko_fi: senigami
custom: ["https://buymeacoffee.com/senigami"]

# Uncomment and fill in if/when you set this up (free to join):
# open_collective: audiobook-studio
