import pytest
from unittest.mock import patch, MagicMock
from pathlib import Path
from app.engines import assemble_audiobook

def test_assemble_audiobook_ffmpeg_command_structure(tmp_path):
    """
    Verifies that the FFmpeg command generated by assemble_audiobook 
    includes the cover input and mapping when a valid cover_path is provided.
    """
    input_folder = tmp_path / "test_audio"
    input_folder.mkdir()
    (input_folder / "chapter1.mp3").write_text("audio data")

    book_title = "Test Book"
    output_m4b = tmp_path / "test_book.m4b"

    cover_file = tmp_path / "test_cover.jpg"
    cover_file.write_text("fake image data")
    cover_path = str(cover_file)

    # We still need to mock run_cmd_stream and get_audio_duration
    with patch('app.engines.get_audio_duration', return_value=120.0), \
         patch('app.engines.run_cmd_stream', return_value=0) as mock_run:

        on_output = MagicMock()
        def cancel_check():
            return False

        rc = assemble_audiobook(
            input_folder, book_title, output_m4b, on_output, cancel_check,
            cover_path=cover_path
        )

        assert rc == 0

        # Check that the command contains the cover path and mapping
        cmd = mock_run.call_args[0][0]
        assert f"-i {cover_path}" in cmd
        assert "-map 2:v" in cmd
        assert "-disposition:v:0 attached_pic" in cmd

def test_assemble_audiobook_ffmpeg_no_cover(tmp_path):
    """Verifies that the FFmpeg command does NOT include cover mapping when path is missing."""
    input_folder = tmp_path / "test_audio"
    input_folder.mkdir()
    (input_folder / "chapter1.mp3").write_text("audio data")

    book_title = "Test Book"
    output_m4b = tmp_path / "test_book.m4b"

    with patch('app.engines.get_audio_duration', return_value=120.0), \
         patch('app.engines.run_cmd_stream', return_value=0) as mock_run:

        on_output = MagicMock()
        def cancel_check():
            return False

        # No cover_path provided
        rc = assemble_audiobook(
            input_folder, book_title, output_m4b, on_output, cancel_check
        )

        assert rc == 0
        cmd = mock_run.call_args[0][0]
        # map 2:v refers to the 3rd input (cover), which should be missing
        assert "-map 2:v" not in cmd
        assert "disposition:v:0 attached_pic" not in cmd
