/**
 * exportArchetypePortraitPrompts.ts — reusable dev tool (owner ask, 2026-07-17).
 *
 * Regenerates design-docs/reference/voice-archetypes/default-portrait-prompts.md:
 * one section per archetype in the character library, each with its exact
 * filename slug and its flat/generic default-portrait prompt
 * (`buildSimpleArchetypeIconPrompt()` in
 * frontend/src/pages/Voices/components/metadata/simpleArchetypeIcon.ts — the
 * single source of truth for both the prompt text and the slug, so this
 * script can never drift from what the app actually looks up at
 * `frontend/public/archetype-portraits/<slug>.png`).
 *
 * Run with: npm run export:archetype-portraits (from frontend/)
 * Re-run any time archetypes are added to voice_archetypes.json — the sheet
 * always reflects the full current list, so keeping new characters styled
 * consistently with the rest is a one-command operation.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { recordingArchetypes } from '../src/pages/Voices/components/metadata/recordingArchetypes';
import { buildSimpleArchetypeIconPrompt, slugifyArchetypeName } from '../src/pages/Voices/components/metadata/simpleArchetypeIcon';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../../design-docs/reference/voice-archetypes/default-portrait-prompts.md');

function buildSheet(): string {
    const lines: string[] = [];
    lines.push('# Default character portrait prompts');
    lines.push('');
    lines.push(
        `Generated by \`npm run export:archetype-portraits\` (frontend/scripts/exportArchetypePortraitPrompts.ts) — ${recordingArchetypes.length} archetypes.`,
    );
    lines.push('');
    lines.push(
        'For each row: feed the prompt into an image generator, save the result as `<slug>.png`, and drop it in ' +
        '`frontend/public/archetype-portraits/` — the picker looks it up by that exact slug automatically. ' +
        'Regenerate this file (rerun the command above) any time a new archetype is added.',
    );
    lines.push('');
    for (const archetype of recordingArchetypes) {
        lines.push(`## ${archetype.archetype_name}`);
        lines.push('');
        lines.push(`- **slug (save as):** \`${slugifyArchetypeName(archetype.archetype_name)}.png\``);
        lines.push('- **prompt:**');
        lines.push('');
        lines.push('  ```');
        lines.push(`  ${buildSimpleArchetypeIconPrompt(archetype)}`);
        lines.push('  ```');
        lines.push('');
    }
    return lines.join('\n');
}

writeFileSync(OUTPUT_PATH, buildSheet(), 'utf-8');
console.log(`Wrote ${recordingArchetypes.length} archetype portrait prompts to ${OUTPUT_PATH}`);
