/**
 * Voice archetype → recording prompt guide — statically bundled from
 * design-docs/reference/voice-archetypes/voice_archetypes.json (39 rows).
 * Update both this const and the source JSON when the archetype table changes.
 */

export interface RecordingArchetype {
    archetype_name: string;
    class: string;
    gender: string;
    age: string;
    /** Comma-separated tone taxonomy values, e.g. "warm, friendly, gentle" */
    dominant_tones: string;
    /** Comma-separated timbre taxonomy values, e.g. "rich, velvety, smooth" */
    dominant_timbres: string;
    pace: string;
    appearance_creature_type: string;
    appearance_description: string;
    recording_prompt: string;
    direction_note: string;
}

export const recordingArchetypes: RecordingArchetype[] = [
    {
        archetype_name: 'Warm Storyteller',
        class: 'human',
        gender: 'feminine',
        age: 'adult',
        dominant_tones: 'warm, friendly, gentle',
        dominant_timbres: 'rich, velvety, smooth',
        pace: 'measured',
        appearance_creature_type: 'Human — fireside storyteller',
        appearance_description: 'A cozy fireside figure in a hand-knit cardigan, soft rounded features, reading glasses pushed up into greying hair — the kind of person who remembers how you take your tea.',
        recording_prompt: '"Come closer, and let me tell you how it really happened. The old dog nuzzled the basket of warm bread, and nobody had the heart to say no. By the time the kettle sang, we\'d already forgiven each other."',
        direction_note: 'Let warmth bloom on the open vowels, as if you\'re smiling through every sentence.',
    },
    {
        archetype_name: 'Stern Newsreader',
        class: 'human',
        gender: 'masculine',
        age: 'middle-aged',
        dominant_tones: 'authoritative, serious, professional',
        dominant_timbres: 'crisp, clear, resonant',
        pace: 'brisk',
        appearance_creature_type: 'Human — broadcast anchor',
        appearance_description: 'Sharp-suited anchor-desk presence, close-cropped grey hair, unblinking eye contact with the camera, posture like a plumb line.',
        recording_prompt: '"Tonight\'s top story: officials confirmed the bridge closure will extend through Tuesday. Crews report steady progress, though delays remain likely during peak commuter hours. We\'ll have updates as the situation develops."',
        direction_note: 'Hit every consonant like a headline — no syllable allowed to blur.',
    },
    {
        archetype_name: 'Sardonic Noir Detective',
        class: 'human',
        gender: 'masculine',
        age: 'middle-aged',
        dominant_tones: 'sarcastic, deadpan, serious',
        dominant_timbres: 'husky, gravelly, low',
        pace: 'measured',
        appearance_creature_type: 'Human — hardboiled detective',
        appearance_description: 'Trench coat collar up, five-o\'clock shadow, a cigarette that never quite gets lit, eyes that have already guessed the ending.',
        recording_prompt: '"Sure, the dame said she\'d never seen the gun before. Sure, and the rain never falls twice on the same street corner. I\'d bet my last nickel she\'s lying, and I never bet against a sure thing."',
        direction_note: 'Drag the pace half a beat behind the words, like you already know how this ends.',
    },
    {
        archetype_name: 'Energetic Hype Host',
        class: 'human',
        gender: 'masculine',
        age: 'young-adult',
        dominant_tones: 'energetic, upbeat, playful',
        dominant_timbres: 'bright, crisp, light',
        pace: 'fast',
        appearance_creature_type: 'Human — livestream hype host',
        appearance_description: 'Ring-light glow, backwards cap, hands never still, the kind of grin that\'s audible before he even opens his mouth.',
        recording_prompt: '"Okay okay okay, are you ready for this?! Because we are about to smash the biggest giveaway of the year, and I am not exaggerating one single bit! Smash that button, drop a comment, let\'s GO!"',
        direction_note: 'Push the pitch up at the end of every clause like you can\'t wait for the next one.',
    },
    {
        archetype_name: 'Gentle Bedtime Narrator',
        class: 'human',
        gender: 'feminine',
        age: 'adult',
        dominant_tones: 'soothing, calm, gentle',
        dominant_timbres: 'soft, breathy, velvety',
        pace: 'slow',
        appearance_creature_type: 'Human — bedtime-story narrator',
        appearance_description: 'Dim lamplight, an oatmeal-colored cardigan, hands folded loosely around a well-worn storybook, voice pitched for a room that\'s already half asleep.',
        recording_prompt: '"The little fox curled beneath the willow tree, and the moon pulled her blanket of clouds up close. Somewhere far off, an owl hushed the wind. Sleep now; the story will still be here in the morning."',
        direction_note: 'Let each sentence trail softly downward, like you\'re tucking it in.',
    },
    {
        archetype_name: 'Heroic Protagonist',
        class: 'human',
        gender: 'masculine',
        age: 'young-adult',
        dominant_tones: 'heroic, confident, energetic',
        dominant_timbres: 'resonant, clear, rich',
        pace: 'moderate',
        appearance_creature_type: 'Human — fantasy/action hero',
        appearance_description: 'Square-jawed, wind-tousled hair, standing at the edge of a cliff with a hand already reaching for the hilt of something important.',
        recording_prompt: '"We didn\'t come this far to fail now. Raise your shields, hold the line, and remember — every one of us chose to be here. When the gate breaks, we break it right back."',
        direction_note: 'Let your chest lead the sound, as if you\'re rallying troops behind you.',
    },
    {
        archetype_name: 'Menacing Human Villain',
        class: 'human',
        gender: 'masculine',
        age: 'middle-aged',
        dominant_tones: 'sinister, menacing, dramatic',
        dominant_timbres: 'gravelly, low, rough',
        pace: 'slow',
        appearance_creature_type: 'Human — cold antagonist',
        appearance_description: 'Immaculate black coat, a smile that never reaches the eyes, fingers steepled while he waits for you to realize you\'ve already lost.',
        recording_prompt: '"You still think this is a negotiation. How charming. I\'ve already won — I simply enjoy watching you catch up. Go on, struggle a little more; it\'s the only entertainment I get these days."',
        direction_note: 'Savor the consonants like they\'re a private joke only you understand.',
    },
    {
        archetype_name: 'Corporate E-Learning Guide',
        class: 'human',
        gender: 'neutral',
        age: 'adult',
        dominant_tones: 'professional, friendly, confident',
        dominant_timbres: 'clear, crisp, smooth',
        pace: 'moderate',
        appearance_creature_type: 'Human — training-video presenter',
        appearance_description: 'Neutral blazer, tidy desk setup, an approachable smile calibrated for a corporate training thumbnail.',
        recording_prompt: '"In this module, we\'ll cover three key steps: preparing your workspace, reviewing the checklist, and submitting your report. Take a moment to pause the video if you need to catch up. Ready? Let\'s continue."',
        direction_note: 'Keep the energy level and even, like a patient tour guide who\'s said this a hundred times but still means it.',
    },
    {
        archetype_name: 'Sassy Best Friend',
        class: 'human',
        gender: 'feminine',
        age: 'young-adult',
        dominant_tones: 'playful, quirky, sarcastic',
        dominant_timbres: 'bright, light, crisp',
        pace: 'brisk',
        appearance_creature_type: 'Human — comic-relief confidante',
        appearance_description: 'Oversized hoop earrings, scrunched nose mid-laugh, phone in one hand and zero patience for nonsense in the other.',
        recording_prompt: '"Wait, you texted him WHAT at 2 a.m.? Girl. No. We are fixing this immediately, chop chop. Grab your coat, grab the good snacks, and let\'s go pretend this never happened."',
        direction_note: 'Let the pitch skitter up and down like you\'re mid-gossip, never settling on one note.',
    },
    {
        archetype_name: 'Wise Elder Mentor',
        class: 'human',
        gender: 'masculine',
        age: 'senior',
        dominant_tones: 'wise, calm, authoritative',
        dominant_timbres: 'deep, rich, resonant',
        pace: 'measured',
        appearance_creature_type: 'Human — sage mentor',
        appearance_description: 'Weathered hands folded over a walking stick, deep-set eyes that have watched several decades of other people\'s mistakes, unhurried in every gesture.',
        recording_prompt: '"Patience, child. The river doesn\'t rush to reach the sea; it simply never stops moving. Learn that, and the rest of what troubles you will settle on its own."',
        direction_note: 'Let long pauses do half the work — wisdom should never sound rushed.',
    },
    {
        archetype_name: 'Documentary Narrator',
        class: 'human',
        gender: 'masculine',
        age: 'middle-aged',
        dominant_tones: 'serious, authoritative, epic',
        dominant_timbres: 'deep, resonant, rich',
        pace: 'measured',
        appearance_creature_type: 'Human — nature-doc voice',
        appearance_description: 'Unseen presence — tweed elbow patches, a study lined with field notebooks, a voice built for wide aerial shots.',
        recording_prompt: '"Deep beneath the ice, a slow migration has continued unchanged for ten thousand years. Few have ever witnessed it. Tonight, for the first time, we bring you closer than anyone thought possible."',
        direction_note: 'Let each sentence land like a camera slowly pulling back to reveal scale.',
    },
    {
        archetype_name: 'Child Adventurer',
        class: 'human',
        gender: 'neutral',
        age: 'child',
        dominant_tones: 'cheerful, energetic, playful',
        dominant_timbres: 'bright, light, crisp',
        pace: 'brisk',
        appearance_creature_type: 'Human — young explorer',
        appearance_description: 'Scraped knees, a backwards baseball cap, a homemade compass clutched like a treasure map, breathless from running the whole way here.',
        recording_prompt: '"Wait wait wait, I found it! The secret door was behind the bookshelf the whole entire time! Come on, hurry, before my sister figures out where we went!"',
        direction_note: 'Let the excitement spill over the ends of words, like you can barely get the sentence out fast enough.',
    },
    {
        archetype_name: 'Sultry Late-Night DJ',
        class: 'human',
        gender: 'feminine',
        age: 'adult',
        dominant_tones: 'calm, sensual, mysterious',
        dominant_timbres: 'velvety, silky, low',
        pace: 'slow',
        appearance_creature_type: 'Human — radio-booth voice',
        appearance_description: 'Headphones draped around the neck, half-lit studio glow, a slow smile you can hear even with your eyes closed.',
        recording_prompt: '"It\'s late, it\'s quiet, and it\'s just you and me for the next hour. Pour something slow, dim the lights if you\'ve got them, and let this next one wrap around the room."',
        direction_note: 'Let the words melt into each other, never clipping a single ending.',
    },
    {
        archetype_name: 'Drill Sergeant',
        class: 'human',
        gender: 'masculine',
        age: 'middle-aged',
        dominant_tones: 'intense, authoritative, serious',
        dominant_timbres: 'booming, gritty, rough',
        pace: 'fast',
        appearance_creature_type: 'Human — military instructor',
        appearance_description: 'Buzzcut, jaw like a closed fist, boots planted shoulder-width apart, veins standing out on his neck before he\'s even started shouting.',
        recording_prompt: '"Drop and give me twenty, right now, not tomorrow! I want boots laced, packs zipped, and mouths shut in ten seconds flat! Move, move, MOVE!"',
        direction_note: 'Bark each command from the diaphragm, cutting words off hard at the end.',
    },
    {
        archetype_name: 'Teen Social Media Creator',
        class: 'human',
        gender: 'feminine',
        age: 'teen',
        dominant_tones: 'upbeat, quirky, energetic',
        dominant_timbres: 'bright, crisp, light',
        pace: 'fast',
        appearance_creature_type: 'Human — short-form content creator',
        appearance_description: 'Ring-light selfie glow, oversized hoodie, phone held at the exact practiced angle, mid-sentence before the camera even finishes focusing.',
        recording_prompt: '"Okay so this hack literally changed my life and nobody is talking about it enough. You just twist it, snap it, and boom, done, easiest thing ever. Like and follow if you actually tried it!"',
        direction_note: 'Keep it breathless and immediate, like you\'re narrating your own reaction in real time.',
    },
    {
        archetype_name: 'Melancholic Poet',
        class: 'human',
        gender: 'neutral',
        age: 'adult',
        dominant_tones: 'melancholic, somber, gentle',
        dominant_timbres: 'breathy, soft, thin',
        pace: 'slow',
        appearance_creature_type: 'Human — reflective essayist',
        appearance_description: 'Rain-streaked window light, a cup of tea gone cold, a notebook of crossed-out lines, shoulders drawn slightly inward.',
        recording_prompt: '"The house still smells like her, faintly, in the hallway near the coats. I keep the porch light on though no one\'s coming home. Some habits outlive the reason for them."',
        direction_note: 'Let the breath show between phrases, like the words are costing you something to say.',
    },
    {
        archetype_name: 'Gravelly Rock Troll',
        class: 'creature',
        gender: 'masculine',
        age: 'ageless',
        dominant_tones: 'menacing, dramatic, intense',
        dominant_timbres: 'gravelly, gritty, rough',
        pace: 'slow',
        appearance_creature_type: 'Rock troll',
        appearance_description: 'A hulking, moss-crusted figure built from cracked granite plates, knuckles dragging like boulders, lichen growing in the seams of his shoulders.',
        recording_prompt: '"Cross bridge, troll crush. Simple rule. Little goat learn hard way, little goat learn quick way — troll no care which. Rocks remember every footstep; troll remember longer."',
        direction_note: 'Grind each word out slow and low, like stone scraping against stone.',
    },
    {
        archetype_name: 'Booming War-Giant',
        class: 'creature',
        gender: 'masculine',
        age: 'adult',
        dominant_tones: 'epic, heroic, intense',
        dominant_timbres: 'booming, deep, resonant',
        pace: 'measured',
        appearance_creature_type: 'Giant',
        appearance_description: 'A mountain given legs — bronze pauldrons the size of cart wheels, a war-horn slung across a chest wide enough to shelter a wagon.',
        recording_prompt: '"Sound the horn! Let the valley itself hear us coming! No wall built by small hands has ever held against a giant\'s stride!"',
        direction_note: 'Let the low end fill the whole room before the next word arrives.',
    },
    {
        archetype_name: 'Chipper Garden Fairy',
        class: 'creature',
        gender: 'feminine',
        age: 'ageless',
        dominant_tones: 'cheerful, playful, upbeat',
        dominant_timbres: 'high-pitched, bright, light',
        pace: 'fast',
        appearance_creature_type: 'Fairy',
        appearance_description: 'Dragonfly wings dusted with pollen, a dandelion-fluff halo of hair, perched on a mushroom cap and never quite standing still.',
        recording_prompt: '"Ooh, pick that one, pick that one, the pink petal, quick quick quick! We\'ll thread it with dewdrops and it\'ll sparkle for simply ages!"',
        direction_note: 'Let the pitch flit upward at the end of every little phrase, like you\'re hovering, never landing.',
    },
    {
        archetype_name: 'Weary Undead Drone',
        class: 'creature',
        gender: 'masculine',
        age: 'ageless',
        dominant_tones: 'somber, menacing, deadpan',
        dominant_timbres: 'raspy, husky, thin',
        pace: 'slow',
        appearance_creature_type: 'Zombie / undead',
        appearance_description: 'Grey, sunken cheeks, tattered burial cloth hanging loose on a frame gone gaunt, movements a half-beat behind where the body wants to go.',
        recording_prompt: '"Hungry. Always hungry. Was a name once, before the dirt. Walk. Walk. Walk. Forgot what for."',
        direction_note: 'Let each word drop out of you like it costs the last of your air.',
    },
    {
        archetype_name: 'Voice of the Void',
        class: 'deity',
        gender: 'not-applicable',
        age: 'ageless',
        dominant_tones: 'epic, mysterious, authoritative',
        dominant_timbres: 'deep, booming, resonant',
        pace: 'slow',
        appearance_creature_type: 'Cosmic narrator-god',
        appearance_description: 'A face assembled from drifting starlight and shadow, no fixed form, words seeming to arrive from every direction of a vast dark room at once.',
        recording_prompt: '"Before light, there was only the question of light. Before time, there was only the patience to wait for it. You are here because I allowed a single second to pass."',
        direction_note: 'Let silence stretch before each sentence, as if the words have existed longer than you have.',
    },
    {
        archetype_name: 'Radiant Guardian Angel',
        class: 'deity',
        gender: 'feminine',
        age: 'ageless',
        dominant_tones: 'warm, gentle, wise',
        dominant_timbres: 'clear, bright, smooth',
        pace: 'measured',
        appearance_creature_type: 'Angel',
        appearance_description: 'Wings folded like tempered glass catching the light, robes that seem lit from within, a stillness that makes the air around her feel safer.',
        recording_prompt: '"You are not alone here, and you never were. Set down what you\'ve been carrying — I have you now. Rest; I will keep watch until the light returns."',
        direction_note: 'Let the warmth ring through the clear tone like sun through stained glass.',
    },
    {
        archetype_name: 'Mischievous Forest Gnome',
        class: 'creature',
        gender: 'masculine',
        age: 'ageless',
        dominant_tones: 'playful, quirky, friendly',
        dominant_timbres: 'nasal, high-pitched, crisp',
        pace: 'brisk',
        appearance_creature_type: 'Gnome',
        appearance_description: 'A stout figure barely knee-high, pointed red cap askew, beard full of twigs and stolen trinkets, boots that squeak with every hurried step.',
        recording_prompt: '"Psst! Over here, over here, behind the toadstool! I\'ve got a shortcut, a proper shortcut, quicker than the crow and twice as clever!"',
        direction_note: 'Keep the nasal buzz bright and quick, like you\'re always halfway to a joke.',
    },
    {
        archetype_name: 'Sly Goblin Scavenger',
        class: 'creature',
        gender: 'masculine',
        age: 'ageless',
        dominant_tones: 'sarcastic, quirky, sinister',
        dominant_timbres: 'raspy, nasal, gritty',
        pace: 'brisk',
        appearance_creature_type: 'Goblin',
        appearance_description: 'Hunched and wiry, patchwork leather scavenged from a dozen owners, ears too big for his skull and a grin with several teeth missing.',
        recording_prompt: '"Ooh, shiny. Mine now, obviously. Finders keepers, losers cry about it later — that\'s the rule, I just made it up, but it\'s still the rule."',
        direction_note: 'Snap the consonants sharp and greedy, like you\'re already reaching for the next thing.',
    },
    {
        archetype_name: 'Sturdy Mountain Dwarf',
        class: 'creature',
        gender: 'masculine',
        age: 'adult',
        dominant_tones: 'serious, warm, authoritative',
        dominant_timbres: 'low, gravelly, booming',
        pace: 'measured',
        appearance_creature_type: 'Dwarf',
        appearance_description: 'Barrel-chested, braided beard clasped in iron rings, forearms like anvils, boots planted as if the mountain itself agreed to hold him up.',
        recording_prompt: '"This tunnel was carved by my grandfather\'s grandfather, and it will outlast every one of us standing here. Respect the stone, and the stone respects you back. Now — who\'s thirsty?"',
        direction_note: 'Let the low register settle like weight, unhurried and immovable.',
    },
    {
        archetype_name: 'Cackling Swamp Witch',
        class: 'creature',
        gender: 'feminine',
        age: 'senior',
        dominant_tones: 'sinister, playful, menacing',
        dominant_timbres: 'raspy, husky, nasal',
        pace: 'variable',
        appearance_creature_type: 'Witch / crone',
        appearance_description: 'Hunched over a bubbling cauldron, warts and all, a shawl of dried herbs and small bones, fingernails curled like withered roots.',
        recording_prompt: '"Ehehe, come closer dearie, closer still — the potion needs just one more little thing. A pinch of newt, a drop of spite, and oh, your voice would do nicely."',
        direction_note: 'Let the pace lurch unpredictably, cackling faster then slowing to a wicked drawl.',
    },
    {
        archetype_name: 'Seductive Siren',
        class: 'creature',
        gender: 'feminine',
        age: 'ageless',
        dominant_tones: 'sensual, mysterious, calm',
        dominant_timbres: 'silky, velvety, breathy',
        pace: 'slow',
        appearance_creature_type: 'Siren',
        appearance_description: 'Scales shimmering faintly at the hairline, hair perpetually damp as if just risen from black water, a stillness that draws the eye before the voice even starts.',
        recording_prompt: '"Closer now. The water\'s warmer than it looks, I promise you that much. Just a few more steps... you won\'t need to swim back."',
        direction_note: 'Let every word pull the listener forward like a slow undertow.',
    },
    {
        archetype_name: 'Whispering Ghost',
        class: 'creature',
        gender: 'ambiguous',
        age: 'ageless',
        dominant_tones: 'mysterious, melancholic, somber',
        dominant_timbres: 'breathy, thin, soft',
        pace: 'slow',
        appearance_creature_type: 'Ghost',
        appearance_description: 'Translucent at the edges, a Victorian collar frayed to lace, feet that never quite touch the floorboards she\'s still haunting.',
        recording_prompt: '"I left the candle burning for him. Thirty years, and it\'s still burning. Can you feel how cold this room gets, or is it only me who remembers?"',
        direction_note: 'Let the breath outweigh the voice, like the words are barely holding together.',
    },
    {
        archetype_name: 'Ancient Dragon Overlord',
        class: 'creature',
        gender: 'masculine',
        age: 'ageless',
        dominant_tones: 'epic, menacing, authoritative',
        dominant_timbres: 'booming, deep, resonant',
        pace: 'slow',
        appearance_creature_type: 'Dragon',
        appearance_description: 'Scales like tarnished bronze plate armor, a jaw that could swallow a wagon whole, smoke curling lazily from nostrils that haven\'t needed to hurry in a thousand years.',
        recording_prompt: '"Kingdoms rise, kingdoms fall, and still I am here, patient as the mountain beneath me. Bring me gold, or bring me nothing — either way, I will still be waiting when you\'re gone."',
        direction_note: 'Let each syllable rumble with contained heat, like restraint is the scariest part.',
    },
    {
        archetype_name: 'Silken-Tongued Demon',
        class: 'creature',
        gender: 'masculine',
        age: 'ageless',
        dominant_tones: 'sinister, sensual, villainous',
        dominant_timbres: 'smooth, velvety, low',
        pace: 'measured',
        appearance_creature_type: 'Demon',
        appearance_description: 'Impeccably tailored in charcoal and crimson, horns filed to a polite point, a handshake that\'s somehow already a signature.',
        recording_prompt: '"Oh, don\'t sign in such a hurry — savor it. Everything you want is right here on this one line, and everything you owe is just... details. Shall we?"',
        direction_note: 'Let charm slide over every syllable, so the danger only shows in retrospect.',
    },
    {
        archetype_name: 'Giggling Pixie Sprite',
        class: 'creature',
        gender: 'feminine',
        age: 'ageless',
        dominant_tones: 'playful, cheerful, quirky',
        dominant_timbres: 'high-pitched, light, bright',
        pace: 'fast',
        appearance_creature_type: 'Pixie / sprite',
        appearance_description: 'No bigger than a thumb, wings like stained-glass fragments, hair that changes color when she\'s excited — which is constantly.',
        recording_prompt: '"Tickle tickle tickle, catch me if you can, you can\'t, you can\'t, nobody ever can! Ooh, shiny button, is that for me? It\'s for me now!"',
        direction_note: 'Let the giggle bubble up mid-word, never quite finishing a sentence in a straight line.',
    },
    {
        archetype_name: 'Grinding Stone Golem',
        class: 'creature',
        gender: 'not-applicable',
        age: 'ageless',
        dominant_tones: 'serious, intense, deadpan',
        dominant_timbres: 'booming, rough, distorted',
        pace: 'slow',
        appearance_creature_type: 'Golem',
        appearance_description: 'Hewn from raw quarry stone bound with glowing rune-seams, joints that grind visible dust with every motion, expressionless carved features.',
        recording_prompt: '"Command. Received. Protect the gate. Protect the gate. Enemy detected — enemy... will be... removed."',
        direction_note: 'Let each word land with a full stop, like gears clicking into place one at a time.',
    },
    {
        archetype_name: 'Wailing Banshee',
        class: 'creature',
        gender: 'feminine',
        age: 'ageless',
        dominant_tones: 'dramatic, menacing, melancholic',
        dominant_timbres: 'raspy, husky, distorted',
        pace: 'variable',
        appearance_creature_type: 'Banshee',
        appearance_description: 'Trailing grey shroud that never touches the ground, hair whipped by a wind only she feels, a mouth that opens wider than a face should allow.',
        recording_prompt: '"Someone in this house will not see morning. I have already begun to grieve them. Can you hear it, the sound that means it\'s you?"',
        direction_note: 'Let the volume swell suddenly then collapse to a whisper, like grief you can\'t control.',
    },
    {
        archetype_name: 'Elder Elf Sage',
        class: 'creature',
        gender: 'neutral',
        age: 'ageless',
        dominant_tones: 'wise, calm, mysterious',
        dominant_timbres: 'clear, resonant, smooth',
        pace: 'measured',
        appearance_creature_type: 'Elf',
        appearance_description: 'Silver hair braided with living vines, ears tapering to fine points, eyes that seem to focus on something centuries away.',
        recording_prompt: '"The trees remember the war you\'ve only read about. Sit, and I will tell you what the roots told me. It will take longer than you expect — truth usually does."',
        direction_note: 'Let the clarity ring like a struck bell, unhurried and precise.',
    },
    {
        archetype_name: 'Cold Precision AI Assistant',
        class: 'synthetic',
        gender: 'not-applicable',
        age: 'ageless',
        dominant_tones: 'professional, calm, deadpan',
        dominant_timbres: 'robotic, clear, crisp',
        pace: 'moderate',
        appearance_creature_type: 'Robot / AI assistant',
        appearance_description: 'A faint blue interface glow with no fixed body, waveform pulses syncing to each syllable, every surface polished to a sterile, functional shine.',
        recording_prompt: '"Task received. Processing input across three parameters. Confidence level: ninety-eight percent. Awaiting your next command."',
        direction_note: 'Keep the rhythm perfectly even, with no rise or fall between words.',
    },
    {
        archetype_name: 'Glitching Service Android',
        class: 'synthetic',
        gender: 'not-applicable',
        age: 'ageless',
        dominant_tones: 'deadpan, quirky, professional',
        dominant_timbres: 'robotic, distorted, clear',
        pace: 'variable',
        appearance_creature_type: 'Android / robot',
        appearance_description: 'Chassis paneling scuffed from years of service, a flickering eye-light that stutters mid-sentence, joints that whir audibly when it turns its head.',
        recording_prompt: '"Wel-welcome to- to Sector Seven. Your order is- is ready. Please- disregard the previous- the previous forty error messages."',
        direction_note: 'Let the pace stutter unevenly, snapping back to normal speed mid-phrase like a signal correcting itself.',
    },
    {
        archetype_name: 'Impish Court Jester',
        class: 'character',
        gender: 'masculine',
        age: 'adult',
        dominant_tones: 'playful, sarcastic, quirky',
        dominant_timbres: 'nasal, crisp, light',
        pace: 'variable',
        appearance_creature_type: 'Jester',
        appearance_description: 'Motley in three clashing colors, bells stitched into pointed shoes, a painted grin that doesn\'t always match what\'s underneath it.',
        recording_prompt: '"Oh, your majesty wants the truth? How delightfully expensive of you. Very well: the duke is a fool, the treasury is empty, and your crown is on backwards. You\'re welcome!"',
        direction_note: 'Bounce the pace unpredictably, like every sentence is secretly a punchline setup.',
    },
    {
        archetype_name: 'Clockwork Puppet',
        class: 'character',
        gender: 'not-applicable',
        age: 'ageless',
        dominant_tones: 'quirky, cheerful, deadpan',
        dominant_timbres: 'thin, clear, light',
        pace: 'brisk',
        appearance_creature_type: 'Clockwork puppet / marionette',
        appearance_description: 'Painted porcelain features fixed in a permanent smile, a brass key protruding from its back, joints that click audibly at each gesture.',
        recording_prompt: '"Wind me up, wind me up, and I\'ll dance until you stop! Tick tock, tick tock, that\'s the only song I know! Again? Again? Again!"',
        direction_note: 'Keep the rhythm metronome-steady, like the words themselves are wound by a key.',
    },
    {
        archetype_name: 'Brutish Ogre Enforcer',
        class: 'creature',
        gender: 'masculine',
        age: 'adult',
        dominant_tones: 'intense, menacing, serious',
        dominant_timbres: 'gravelly, rough, booming',
        pace: 'slow',
        appearance_creature_type: 'Ogre',
        appearance_description: 'Slab-muscled and lopsided, tusks jutting from an underbite, a club dragging a groove in the dirt behind him wherever he lumbers.',
        recording_prompt: '"Boss say pay up. You no pay up, boss say I get creative. Ogre very creative. Ogre also very impatient."',
        direction_note: 'Let the words come slow and heavy, like thinking itself takes physical effort.',
    },
];
